### ISSUE TITLE
App keeps crashing on homey

### ISSUE THREAD

**Issue by iAmRenzo** [abaretta/nu.baretta.tplink#13] opened 2020-07-31 10:11 UTC
The app keeps crashing on homey (suddenly stopped). At random. Devices stay offline after restart.

**Comment by iAmRenzo** [comment] 2020-08-19 05:30
If you need logs, a diagnostic code, or anything to debug... happy to help.

**Comment by abaretta** [comment] 2020-09-28 09:46
As explained in a previous issue, this is caused by an interaction with instable networking and the retry mechanism in the underlying library used in the app. When this library is updated (possibly with a fix), the update will be included in the Homey app. 

For now your best bet is to look at your wireless network and see it can be made more stable, as this issue is triggered by underlying (wireless) connectivity issues.

**Closed as completed by abaretta** 2020-09-28 09:46 UTC

**Comment by abaretta** [comment] 2020-10-05 08:16
This issue is resolved in v1.1.12.
